- .github/ISSUE_TEMPLATE/false-positive.md
- .github/pull_request_template.md
- README.md
- src/main/java/com/deque/axe/android/AxeResult.java
- src/main/java/com/deque/axe/android/AxeRuleResult.java
- src/test/java/com/deque/axe/android/AxeResultTest.java
> feat: Add query function to help filter results.

- .circleci/config.yml
> chore: Fix Circle CI YML Configuration.

- .circleci/config.yml
> chore: Change fingerprint for Circle CI build.

- .circleci/config.yml
- .github/ISSUE_TEMPLATE/false-positive.md
- .github/pull_request_template.md
- README.md
- src/main/java/com/deque/axe/android/AxeResult.java
- src/main/java/com/deque/axe/android/AxeRuleResult.java
- src/test/java/com/deque/axe/android/AxeResultTest.java
Resolve regression related to querying for VIOLATION status results only in application.
> fix: release 0.1.0

- src/main/java/com/deque/axe/android/wrappers/AxePoint.java
> fix: Make AxePoint a public API.

- .circleci/release_management_scripts/merge.sh
- src/main/java/com/deque/axe/android/AxeView.java
- src/main/java/com/deque/axe/android/rules/hierarchy/ActiveViewName.java
- src/test/resources/test_specs/play_store.json
> fix: Speakable text recurses children.

- src/main/java/com/deque/axe/android/rules/hierarchy/TouchSizeWcag.java
> fix: Update target size to 44.

- src/main/java/com/deque/axe/android/utils/JsonSerializable.java
Axe images should serialize down to one base 64 string now.
> fix: Axe Image Serialization Fix

- src/main/java/com/deque/axe/android/AxeContext.java
- src/main/java/com/deque/axe/android/AxeMetaData.java
- src/main/java/com/deque/axe/android/AxeRuleResult.java
- src/main/java/com/deque/axe/android/AxeView.java
- src/test/java/com/deque/axe/android/AxeTest.java
- src/test/resources/test_specs/basic_image_view.json
~~- Public API has not changed.~~
> feat: Add AxeMetaData. Modify JSON Serialization so axeViewIds are strings.

- src/main/java/com/deque/axe/android/AxeContext.java
- src/main/java/com/deque/axe/android/AxeMetaData.java
- src/main/java/com/deque/axe/android/AxeView.java
- src/test/java/com/deque/axe/android/AxeTest.java
- src/test/java/com/deque/axe/android/wrappers/AxeViewBuilder.java
> feat: Expand public API for AxeMetaData.

- src/main/java/com/deque/axe/android/AxeView.java
> refactor: Ditch hex string and just use integer toString.

- src/main/java/com/deque/axe/android/rules/hierarchy/base/TouchSize.java
- src/main/java/com/deque/axe/android/wrappers/AxeProps.java
> fix: TouchTargetSize is incomplete when partially offscreen.

- src/main/java/com/deque/axe/android/AxeContext.java
- src/main/java/com/deque/axe/android/AxeMetaData.java
- src/main/java/com/deque/axe/android/AxeRuleResult.java
- src/main/java/com/deque/axe/android/AxeView.java
- src/main/java/com/deque/axe/android/constants/Constants.java
- src/test/java/com/deque/axe/android/AxeResultTest.java
- src/test/java/com/deque/axe/android/AxeTest.java
- src/test/java/com/deque/axe/android/AxeViewTest.java
- src/test/java/com/deque/axe/android/wrappers/AxeViewBuilder.java
- src/test/resources/test_specs/app_color_contrast.json
- src/test/resources/test_specs/play_store.json
> feat: Add Screen Title and other properties to Axe Results objects.

- src/main/java/com/deque/axe/android/AxeView.java
> fix: Add null safety to AxeView.isContentView()

- src/main/java/com/deque/axe/android/AxeView.java
> fix: ignore null result from NodeInfoCompat viewIdResourceName

- src/main/java/com/deque/axe/android/AxeDevice.java
- src/test/java/com/deque/axe/android/AxeDeviceTest.java
Closes: #46
Rationale: The operating system will always generically be Android and doesn't need a user to set it.
> feat: Add default os property to AxeDevice

- src/main/java/com/deque/axe/android/AxeRuleResult.java
- src/main/java/com/deque/axe/android/AxeView.java
- src/main/java/com/deque/axe/android/utils/AxeTree.java
> chore: Generalize AxeRuleResult to take AxeTree instead of AxeView.

- .circleci/config.yml
> chore: Maven Central Publishing

- src/main/java/com/deque/axe/android/AxeView.java
- src/main/java/com/deque/axe/android/wrappers/AxeProps.java
- src/test/java/com/deque/axe/android/wrappers/AxeViewBuilder.java
Closes: https://app.zenhub.com/workspaces/mobile-5ccf5c056202ac26f233076a/issues/dequelabs/axe-android-app/109
> chore: Add Hint Text To Axe View

- src/main/java/com/deque/axe/android/AxeView.java
- src/test/java/com/deque/axe/android/wrappers/AxeViewBuilder.java
Closes: https://app.zenhub.com/workspaces/mobile-5ccf5c056202ac26f233076a/issues/dequelabs/axe-android-app/114
> chore: Add Value to the Axe View

- src/main/java/com/deque/axe/android/rules/hierarchy/ColorContrast.java
Closes: https://app.zenhub.com/workspaces/mobile-5ccf5c056202ac26f233076a/issues/dequelabs/axe-android-app/104
> fix: Off Screen check for Color Contrast

- .circleci/circle_publish_release.sh
- build.gradle
> fix: Added ArtifactId to Maven Central Publishing Task

- src/main/java/com/deque/axe/android/AxeView.java
- src/main/java/com/deque/axe/android/constants/AndroidClassNames.java
- src/main/java/com/deque/axe/android/constants/Constants.java
- src/main/java/com/deque/axe/android/rules/hierarchy/ActiveViewName.java
- src/main/java/com/deque/axe/android/rules/hierarchy/CheckBoxName.java
- src/main/java/com/deque/axe/android/rules/hierarchy/EditTextName.java
- src/main/java/com/deque/axe/android/rules/hierarchy/SwitchName.java
- src/main/java/com/deque/axe/android/rules/hierarchy/base/ActiveView.java
- src/main/java/com/deque/axe/android/rules/hierarchy/base/ModifiableViewName.java
> fix: CheckboxName and SwitchName rule

- src/main/java/com/deque/axe/android/AxePropCalculator.java
- src/main/java/com/deque/axe/android/AxeView.java
- src/test/java/com/deque/axe/android/AxeViewTest.java
Closes: << Issue Number >> OR DELETE
> fix: Calculated Props Bug

- build.gradle
- src/main/java/com/deque/axe/android/AxeConf.java
- src/main/java/com/deque/axe/android/AxeRule.java
- src/main/java/com/deque/axe/android/AxeRuleStateful.java
- src/main/java/com/deque/axe/android/AxeRuleViewHierarchy.java
- src/main/java/com/deque/axe/android/rules/hierarchy/ColorContrast.java
- src/test/java/com/deque/axe/android/AxeTest.java
- src/test/resources/test_specs/app_active_views.json
> feat: Custom Rule Sets

- .circleci/circle_build_and_test.sh
- .circleci/env.sh
- .github/CODEOWNERS
- build.gradle
- src/main/java/com/deque/axe/android/AxeConf.java
- src/test/java/com/deque/axe/android/AxeTest.java
Closes: dequelabs/axe-android-app#125
> fix: Stop making build successful if tests fail

- build.gradle
- src/test/java/com/deque/axe/android/rules/hierarchy/ActiveViewNameTest.java
- src/test/java/com/deque/axe/android/rules/hierarchy/CheckBoxNameTest.java
- src/test/java/com/deque/axe/android/rules/hierarchy/EditTextNameTest.java
- src/test/java/com/deque/axe/android/rules/hierarchy/EditTextValueTest.java
- src/test/java/com/deque/axe/android/rules/hierarchy/ImageViewNameTest.java
- src/test/java/com/deque/axe/android/rules/hierarchy/SwitchNameTest.java
- src/test/java/com/deque/axe/android/rules/hierarchy/TouchSizeWcagTest.java
> chore: Unit tests for Rules

- src/main/java/com/deque/axe/android/AxeView.java
> fix: Axe Context Screen Title

- src/main/java/com/deque/axe/android/rules/hierarchy/CheckBoxName.java
- src/main/java/com/deque/axe/android/rules/hierarchy/EditTextName.java
- src/main/java/com/deque/axe/android/rules/hierarchy/SwitchName.java
- src/main/java/com/deque/axe/android/rules/hierarchy/base/ModifiableViewName.java
- src/main/java/com/deque/axe/android/rules/stateful/DontMoveAccessibilityFocus.java
> fix: Rule WCAG mappings

- .github/CODEOWNERS
- src/test/java/com/deque/axe/android/AxeTest.java
- src/test/java/com/deque/axe/android/rules/hierarchy/ActiveViewNameTest.java
- src/test/java/com/deque/axe/android/rules/hierarchy/CheckBoxNameTest.java
- src/test/java/com/deque/axe/android/rules/hierarchy/EditTextNameTest.java
- src/test/java/com/deque/axe/android/rules/hierarchy/EditTextValueTest.java
- src/test/java/com/deque/axe/android/rules/hierarchy/ImageViewNameTest.java
- src/test/java/com/deque/axe/android/rules/hierarchy/SwitchNameTest.java
- src/test/java/com/deque/axe/android/rules/hierarchy/TouchSizeWcagTest.java
- src/test/java/com/deque/axe/android/utils/AxeJankyPng.java
- src/test/resources/api_test_spec/api_test.json
> chore: Api tests code owner

- .circleci/circle_build_and_test.sh
- .circleci/config.yml
- src/test/java/com/deque/axe/android/rules/hierarchy/ActiveViewNameTest.java
> fix: Change Management bug

- src/main/java/com/deque/axe/android/AxeConf.java
- src/test/java/com/deque/axe/android/AxeTest.java
> chore: Remove added rules list from Axe Conf

- src/main/java/com/deque/axe/android/AxeRuleViewHierarchy.java
- src/main/java/com/deque/axe/android/AxeView.java
- src/main/java/com/deque/axe/android/rules/hierarchy/EditTextValue.java
- src/main/java/com/deque/axe/android/rules/hierarchy/ImageViewName.java
- src/main/java/com/deque/axe/android/rules/hierarchy/base/ActiveView.java
- src/main/java/com/deque/axe/android/rules/hierarchy/base/InformativeView.java
- src/main/java/com/deque/axe/android/rules/hierarchy/base/ModifiableViewName.java
- src/main/java/com/deque/axe/android/wrappers/AxeProps.java
- src/test/java/com/deque/axe/android/rules/hierarchy/ActiveViewNameTest.java
- src/test/java/com/deque/axe/android/rules/hierarchy/EditTextValueTest.java
- src/test/java/com/deque/axe/android/rules/hierarchy/ImageViewNameTest.java
- src/test/java/com/deque/axe/android/wrappers/AxeViewBuilder.java
- src/test/resources/api_test_spec/api_test.json
> feat: Capability to capture Accessibility Delegate

- src/main/java/com/deque/axe/android/AxeRuleResult.java
> feat: Added public constructor for AxeRuleResults.

- build.gradle
> fix: Artifact Id

- .circleci/config.yml
> chore: Update release process

- .github/semantic.yml
> chore: Add Deque angular commit types

- .github/semantic.yml
> chore: Use types instead of type

- .circleci/config.yml
- .github/semantic.yml
- src/main/java/com/deque/axe/android/constants/AxeImpact.java
> chore: Rebase QA 11/11/2020

- src/main/java/com/deque/axe/android/AxeConf.java
- src/main/java/com/deque/axe/android/AxeView.java
> fix: Removes forEach since it is not supported in Android 22 and 23

- src/main/java/com/deque/axe/android/AxeConf.java
- src/main/java/com/deque/axe/android/AxeView.java
> chore: Merge qa down to develop

- src/main/java/com/deque/axe/android/AxeView.java
- src/main/java/com/deque/axe/android/rules/hierarchy/ColorContrast.java
- src/main/java/com/deque/axe/android/rules/hierarchy/base/TouchSize.java
- src/main/java/com/deque/axe/android/wrappers/AxeProps.java
- src/test/java/com/deque/axe/android/AxeViewTest.java
> chore: Use measured height and measured width for calculating Touch Target Size

- src/main/java/com/deque/axe/android/AxeRuleViewHierarchy.java
- src/main/java/com/deque/axe/android/colorcontrast/AxeImage.java
- src/main/java/com/deque/axe/android/colorcontrast/ColorContrastResult.java
- src/main/java/com/deque/axe/android/rules/hierarchy/ColorContrast.java
- src/test/java/com/deque/axe/android/AxeTest.java
- src/test/java/com/deque/axe/android/ColorContrastTests.java
Closes: [issue](https://app.zenhub.com/workspaces/mobile-5ccf5c056202ac26f233076a/issues/dequelabs/sauron/153)
> fix: Color Contrast Rule false positives
